ERROR - 2022-08-28 20:55:35 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\isceeradmin\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\isceeradmin\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'isceer', 3306, '', 0)
#1 C:\xampp\htdocs\isceeradmin\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\isceeradmin\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\isceeradmin\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\isceeradmin\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\isceeradmin\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\isceeradmin\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\isceeradmin\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(36): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->register()
#10 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#11 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\isceeradmin\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\isceeradmin\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\isceeradmin\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\isceeradmin\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\isceeradmin\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#4 C:\xampp\htdocs\isceeradmin\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#5 C:\xampp\htdocs\isceeradmin\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, false)
#6 C:\xampp\htdocs\isceeradmin\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#7 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(36): CodeIgniter\BaseModel->save(Array)
#8 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->register()
#9 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#10 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#12 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2022-08-28 20:55:35 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`nama`, `institusi`, `email`, `password`, `phone`) VALUES (:nama:, :institusi:, :email:, :password:, :phone:)', [...], false)
 3 SYSTEMPATH\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(738): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(666): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(658): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\Signup.php(36): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Signup->register()
 9 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
10 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-08-28 20:56:53 --> mysqli_sql_exception: Column 'phone' cannot be null in C:\xampp\htdocs\isceeradmin\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\isceeradmin\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\isceeradmin\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\isceeradmin\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\isceeradmin\system\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\isceeradmin\system\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\isceeradmin\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\isceeradmin\system\Model.php(666): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\isceeradmin\system\BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(36): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->register()
#10 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#11 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2022-08-28 20:56:53 --> Column 'phone' cannot be null
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `user` (`nama`, `institusi`, `email`, `password`, `phone`) VALUES (\'Herrysa\', \'1\', \'agisabhi28@gmail.com\', \'agisabhi\', NULL)', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `user` (`nama`, `institusi`, `email`, `password`, `phone`) VALUES (\'Herrysa\', \'1\', \'agisabhi28@gmail.com\', \'agisabhi\', NULL)')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `user` (`nama`, `institusi`, `email`, `password`, `phone`) VALUES (\'Herrysa\', \'1\', \'agisabhi28@gmail.com\', \'agisabhi\', NULL)')
 4 SYSTEMPATH\Database\BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `user` (`nama`, `institusi`, `email`, `password`, `phone`) VALUES (:nama:, :institusi:, :email:, :password:, :phone:)', [...], false)
 5 SYSTEMPATH\Model.php(278): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(738): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(666): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(658): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\Signup.php(36): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Signup->register()
11 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
12 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-28 21:41:58 --> Undefined constant "App\Controllers\now"
in APPPATH\Controllers\Signup.php on line 49.
 1 APPPATH\Controllers\Signup.php(42): App\Controllers\Signup->sendEmail('prayoga_bila@email.unikom.ac.id', 'jumadi')
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Signup->register()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-08-28 21:48:34 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\isceeradmin\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717)
#1 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1717): mail('prayoga_bila@em...', '=?UTF-8?Q?Activ...', 'This is a multi...', 'Date: Sun, 28 A...', '-f injuratech@e...')
#2 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(56): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(42): App\Controllers\Signup->sendEmail('prayoga_bila@em...', 'yoga-ardila')
#6 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->register()
#7 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#8 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
ERROR - 2022-08-28 22:01:33 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\isceeradmin\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717)
#1 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1717): mail('timkonferensi@e...', '=?UTF-8?Q?Activ...', 'This is a multi...', 'Date: Sun, 28 A...', '-f injuratech@e...')
#2 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(56): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(42): App\Controllers\Signup->sendEmail('timkonferensi@e...')
#6 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->register()
#7 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#8 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
ERROR - 2022-08-28 22:08:54 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\isceeradmin\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717)
#1 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1717): mail('agisabhi28@gmai...', '=?UTF-8?Q?Activ...', 'This is a multi...', 'Date: Sun, 28 A...', '-f injuratech@e...')
#2 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(56): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(42): App\Controllers\Signup->sendEmail('agisabhi28@gmai...')
#6 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->register()
#7 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#8 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}
ERROR - 2022-08-28 22:40:20 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\isceeradmin\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717)
#1 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1717): mail('agisabhi28@gmai...', '=?UTF-8?Q?Activ...', 'This is a multi...', 'Date: Sun, 28 A...', '-f injuratech@e...')
#2 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(57): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->sendEmail()
#6 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#7 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-08-28 22:42:49 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\isceeradmin\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717)
#1 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1717): mail('prayoga_bila@em...', '=?UTF-8?Q?Activ...', 'This is a multi...', 'Date: Sun, 28 A...', '-f agisabhi28@g...')
#2 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(57): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->sendEmail()
#6 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#7 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-08-28 22:46:06 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\isceeradmin\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717)
#1 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1717): mail('agisabhi28@gmai...', '=?UTF-8?Q?Activ...', 'This is a multi...', 'Date: Sun, 28 A...', '-f agisabhi28@g...')
#2 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(57): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->sendEmail()
#6 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#7 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-08-28 22:46:57 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\isceeradmin\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717)
#1 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1717): mail('agisabhi28@gmai...', '=?UTF-8?Q?Activ...', 'This is a multi...', 'Date: Sun, 28 A...', '-f agisabhi28@g...')
#2 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(57): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->sendEmail()
#6 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#7 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-08-28 22:47:08 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\isceeradmin\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717)
#1 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1717): mail('agisabhi28@gmai...', '=?UTF-8?Q?Activ...', 'This is a multi...', 'Date: Sun, 28 A...', '-f agisabhi28@g...')
#2 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(57): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->sendEmail()
#6 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#7 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-08-28 22:47:29 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\isceeradmin\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717)
#1 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1717): mail('agisabhi28@gmai...', '=?UTF-8?Q?Activ...', 'This is a multi...', 'Date: Sun, 28 A...', '-f agisabhi28@g...')
#2 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(57): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->sendEmail()
#6 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#7 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-08-28 22:48:20 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\isceeradmin\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717)
#1 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1717): mail('agisabhi28@gmai...', '=?UTF-8?Q?Activ...', 'This is a multi...', 'Date: Sun, 28 A...', '-f agisabhi28@g...')
#2 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(57): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->sendEmail()
#6 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#7 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-08-28 22:52:48 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\isceeradmin\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717)
#1 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1717): mail('prayoga_bila@em...', '=?UTF-8?Q?Activ...', 'This is a multi...', 'Date: Sun, 28 A...', '-f injuratech@e...')
#2 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(57): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->sendEmail()
#6 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#7 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
ERROR - 2022-08-28 22:58:26 --> Email: sendWithMail throwed ErrorException: mail(): Failed to connect to mailserver at &quot;localhost&quot; port 25, verify your &quot;SMTP&quot; and &quot;smtp_port&quot; setting in php.ini or use ini_set() in C:\xampp\htdocs\isceeradmin\system\Email\Email.php:1717
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'mail(): Failed ...', 'C:\\xampp\\htdocs...', 1717)
#1 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1717): mail('prayoga_bila@em...', '=?UTF-8?Q?Activ...', 'This is a multi...', 'Date: Sun, 28 A...', '-f injuratech@e...')
#2 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1654): CodeIgniter\Email\Email->sendWithMail()
#3 C:\xampp\htdocs\isceeradmin\system\Email\Email.php(1552): CodeIgniter\Email\Email->spoolEmail()
#4 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(57): CodeIgniter\Email\Email->send()
#5 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->sendEmail()
#6 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#7 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-08-28 23:24:22 --> Undefined property: App\Controllers\Signup::$db
in APPPATH\Controllers\Signup.php on line 31.
 1 APPPATH\Controllers\Signup.php(31): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined property: App\\Controllers\\Signup::$db', 'APPPATH\\Controllers\\Signup.php', 31)
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Signup->register()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-28 23:26:09 --> Call to undefined method CodeIgniter\Database\MySQLi\Result::num_rows()
in APPPATH\Controllers\Signup.php on line 34.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Signup->register()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-28 23:27:09 --> Call to undefined method CodeIgniter\Database\MySQLi\Result::countAll()
in APPPATH\Controllers\Signup.php on line 34.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Signup->register()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-28 23:28:55 --> Call to undefined method CodeIgniter\Database\MySQLi\Result::countAllResults()
in APPPATH\Controllers\Signup.php on line 34.
 1 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Signup->register()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
 3 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-28 23:29:36 --> url_title(): Argument #1 ($str) must be of type string, null given, called in C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php on line 40
in SYSTEMPATH\Helpers\url_helper.php on line 475.
 1 APPPATH\Controllers\Signup.php(40): url_title(null, '-', true)
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Signup->register()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
ERROR - 2022-08-28 23:33:11 --> mysqli_sql_exception: Not unique table/alias: 'user' in C:\xampp\htdocs\isceeradmin\system\Database\MySQLi\Connection.php:292
Stack trace:
#0 C:\xampp\htdocs\isceeradmin\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\isceeradmin\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\isceeradmin\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\isceeradmin\system\Database\BaseBuilder.php(1669): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php(34): CodeIgniter\Database\BaseBuilder->countAllResults()
#5 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(904): App\Controllers\Signup->register()
#6 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
#7 C:\xampp\htdocs\isceeradmin\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\isceeradmin\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\isceeradmin\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-08-28 23:33:11 --> Not unique table/alias: 'user'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 292.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(292): mysqli->query('SELECT COUNT(*) AS `numrows`
FROM `user`, `user`
WHERE `email` IS NULL', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*) AS `numrows`
FROM `user`, `user`
WHERE `email` IS NULL')
 3 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*) AS `numrows`
FROM `user`, `user`
WHERE `email` IS NULL')
 4 SYSTEMPATH\Database\BaseBuilder.php(1669): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `user`, `user`
WHERE `email` IS NULL', [], false)
 5 APPPATH\Controllers\Signup.php(34): CodeIgniter\Database\BaseBuilder->countAllResults()
 6 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Signup->register()
 7 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
 8 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-08-28 23:34:18 --> url_title(): Argument #1 ($str) must be of type string, null given, called in C:\xampp\htdocs\isceeradmin\app\Controllers\Signup.php on line 40
in SYSTEMPATH\Helpers\url_helper.php on line 475.
 1 APPPATH\Controllers\Signup.php(40): url_title(null, '-', true)
 2 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Signup->register()
 3 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Signup))
 4 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
